# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 868f56d93a0813f83b0cd85c69a86da52a8855e67b09667daea2bf8f45510f424545d230db908bea299a6d1dc49044e28d08f6c16bb0916eb9d6e1e9ccb37f60

test:
  secret_key_base: 43aa60425bfe7b00899721f3c57bd48c0fc405a8f0baad4fe736f8286e35d710a02b7bc1b078a12e841b359f6f75f9a9fda8f8de552618bb3d057f5a0ac01755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
